# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/.Xil/Vivado-18348-DESKTOP-QCQ218O/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg400-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/OV7670_VGA_Dispaly.srcs/sources_1/ip/frame_buffer
    C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/OV7670_VGA_Dispaly.srcs/sources_1/ip/clock
    C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/OV7670_VGA_Dispaly.srcs/sources_1/ip/rgb2dvi_0
  } {
      G:/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      G:/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/OV7670_VGA_Dispaly.srcs/sources_1/ip/frame_buffer
    C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/OV7670_VGA_Dispaly.srcs/sources_1/ip/clock
    C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/OV7670_VGA_Dispaly.srcs/sources_1/ip/rgb2dvi_0
  } {
      C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/.Xil/Vivado-18348-DESKTOP-QCQ218O/realtime/Shift_RAM_3X3_8bit_stub.v
      C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/.Xil/Vivado-18348-DESKTOP-QCQ218O/realtime/frame_buffer_stub.v
      C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/.Xil/Vivado-18348-DESKTOP-QCQ218O/realtime/clock_stub.v
      C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/.Xil/Vivado-18348-DESKTOP-QCQ218O/realtime/rgb2dvi_0_stub.v
      C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/OV7670_VGA_Dispaly.srcs/sources_1/new/I2C_AV_Config.v
      C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/OV7670_VGA_Dispaly.srcs/sources_1/new/I2C_Controller.v
      C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/OV7670_VGA_Dispaly.srcs/sources_1/new/I2C_OV7670_RGB565_Config.v
      C:/Users/11986/Desktop/VGA_Gray_Sobel_HDMI/VGA_Gray_Sobel_HDMI.srcs/sources_1/Img_Processor.v
      C:/Users/11986/Desktop/VGA_Gray_Sobel_HDMI/VGA_Gray_Sobel_HDMI.srcs/sources_1/RGB_YCbCr_Gray.v
      C:/Users/11986/Desktop/VGA_Gray_Sobel_HDMI/VGA_Gray_Sobel_HDMI.srcs/sources_1/Shift_RAM_3X3.v
      C:/Users/11986/Desktop/VGA_Gray_Sobel_HDMI/VGA_Gray_Sobel_HDMI.srcs/sources_1/Sobel_Edge_Detect.v
      C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/OV7670_VGA_Dispaly.srcs/sources_1/new/VGA_Display.v
      C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/OV7670_VGA_Dispaly.srcs/sources_1/new/debounce.v
      C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/OV7670_VGA_Dispaly.srcs/sources_1/new/ov7670_capture.v
      C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/OV7670_VGA_Dispaly.srcs/sources_1/new/ov7670_top.v
    }
      rt::read_vhdl -lib xpm G:/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top ov7670_top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/11986/Desktop/ZYNQ_OV7670_hdmi_Dispaly/.Xil/Vivado-18348-DESKTOP-QCQ218O/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
