# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/11986/Desktop/Dilation_erosion/OV7670_VGA_Dispaly.srcs/sources_1/ip/Shift_RAM_3X3_8bit/Shift_RAM_3X3_8bit.xci
# IP: The module: 'Shift_RAM_3X3_8bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/11986/Desktop/Dilation_erosion/OV7670_VGA_Dispaly.srcs/sources_1/ip/Shift_RAM_3X3_8bit/Shift_RAM_3X3_8bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Shift_RAM_3X3_8bit'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/11986/Desktop/Dilation_erosion/OV7670_VGA_Dispaly.srcs/sources_1/ip/Shift_RAM_3X3_8bit/Shift_RAM_3X3_8bit.xci
# IP: The module: 'Shift_RAM_3X3_8bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/11986/Desktop/Dilation_erosion/OV7670_VGA_Dispaly.srcs/sources_1/ip/Shift_RAM_3X3_8bit/Shift_RAM_3X3_8bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Shift_RAM_3X3_8bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
